# Generated by Django 4.0.5 on 2022-06-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('case_paper_no', models.IntegerField(primary_key=True, serialize=False)),
                ('file_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField()),
                ('telephone', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=300)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'SIMGLE'), ('MARRIED', 'MARRIED'), ('DIVORCE', 'DIVORCE'), ('WIDOW', 'WIDOW')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('food_type', models.CharField(choices=[('VEGETARIAN', 'VEGETARIAN'), ('NON-VEGETARIAN', 'NON-VEGETARIAN'), ('EGGITARIAN', 'EGGITARIAN'), ('OTHER', 'OTHER')], max_length=30, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('reffered_by', models.CharField(max_length=400)),
                ('diagnosis_provisional', models.CharField(max_length=200)),
                ('diangosis_final', models.CharField(max_length=300)),
                ('chief_complaints', models.TextField()),
                ('duration', models.CharField(max_length=200, null=True)),
                ('rx_taken', models.CharField(max_length=300)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
