# Generated by Django 4.0.5 on 2022-07-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
    ]
