# Generated by Django 4.0.5 on 2022-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0003_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
